shellEmulator: true

trustPolicy: no-downgrade

trustPolicyExclude:
  - chokidar@4.0.3
  - undici@5.29.0
catalogs:
  build:
    rolldown: 1.0.0-rc.1
  dev:
    '@actions/core': ^2.0.2
    '@antfu/eslint-config': ^7.2.0
    eslint: ^9.39.2
    nitro: 3.0.1-alpha.2
    typescript: ^5.9.3
    wait-on: ^9.0.3
  lib:
    '@upstash/redis': ^1.36.1
    aws4fetch: ^1.0.20
    ioredis: ^5.9.2
    skland-kit: ^0.3.3
    statocysts: ^0.9.1
    unctx: ^2.5.0
    unstorage: ^2.0.0-alpha.5
  types:
    '@types/node': ^25.0.10
