minimumReleaseAgeExclude:
  - '@types/node@25.9.0'
  - date-fns@4.2.1
  - mima-kit@0.1.2
  - skland-kit@0.3.5
  - statocysts@0.13.0
shellEmulator: true

trustPolicy: no-downgrade

trustPolicyExclude:
  - chokidar@4.0.3
  - undici@5.29.0
catalogs:
  build:
    rolldown: 1.0.0-rc.5
  dev:
    '@actions/core': ^3.0.1
    '@antfu/eslint-config': ^9.2.0
    eslint: ^10.8.0
    nitro: 3.0.1-alpha.2
    typescript: ^6.0.3
    wait-on: ^9.1.0
    wrangler: ^4.114.0
  lib:
    '@upstash/redis': ^1.38.0
    aws4fetch: ^1.0.20
    ioredis: ^5.11.1
    skland-kit: ^0.3.5
    statocysts: ^0.13.0
    unctx: ^3.0.0
    unstorage: ^2.0.0-alpha.7
  types:
    '@types/node': ^25.9.5
allowBuilds:
  esbuild: true
  sharp: true
  workerd: true
